name: Build and Push to Azure Container Registry

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.ACR_LOGIN_SERVER }}/my-app:latest
            ${{ secrets.ACR_LOGIN_SERVER }}/my-app:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Smoke Test - Verify Image Name
        run: |
          # Get the image reference
          IMAGE_REF="${{ secrets.ACR_LOGIN_SERVER }}/my-app:latest"
          
          # Pull the image
          docker pull $IMAGE_REF
          
          # Run the container with a simple command to verify it starts
          CONTAINER_ID=$(docker run -d $IMAGE_REF sh -c "echo 'Image name test'")
          
          # Check if container started successfully
          if [ -z "$CONTAINER_ID" ]; then
            echo "Failed to start container for smoke test"
            exit 1
          fi
          
          # Wait for container to complete
          docker wait $CONTAINER_ID
          
          # Get exit code
          EXIT_CODE=$(docker inspect $CONTAINER_ID --format='{{.State.ExitCode}}')
          
          # Clean up container
          docker rm $CONTAINER_ID
          
          # Check exit code
          if [ "$EXIT_CODE" -ne 0 ]; then
            echo "Smoke test failed with exit code $EXIT_CODE"
            exit $EXIT_CODE
          fi
          
          echo "Smoke test passed: Image name verification successful"