name: Build and Push to Azure Container Registry

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          # Build the Docker image
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/my-app:latest .
          docker tag ${{ secrets.ACR_LOGIN_SERVER }}/my-app:latest ${{ secrets.ACR_LOGIN_SERVER }}/my-app:${{ github.sha }}
          
          # Push to Azure Container Registry
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/my-app:latest
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/my-app:${{ github.sha }}